// Generated by CoffeeScript 1.6.3
(function() {
  var Greeter, Input, Message, dom;

  dom = React.DOM;

  Message = React.createClass({
    render: function() {
      return dom.p({}, "Hello, " + this.props.name + "!");
    }
  });

  Input = React.createClass({
    render: function() {
      return dom.input({
        type: 'text',
        onChange: this.props.updateName
      });
    }
  });

  Greeter = React.createClass({
    defaultName: 'Nobody',
    getInitialState: function() {
      return {
        name: this.defaultName
      };
    },
    doNameUpdate: function(event) {
      if (event.target.value === '') {
        return this.setState({
          name: this.defaultName
        });
      } else {
        return this.setState({
          name: event.target.value
        });
      }
    },
    render: function() {
      return dom.div({}, React.createElement(Message, {
        name: this.state.name
      }), React.createElement(Input, {
        updateName: this.doNameUpdate
      }));
    }
  });

  React.render(React.createElement(Greeter, {}), document.getElementById('my-application'));

}).call(this);
