// Generated by CoffeeScript 1.6.3
(function() {
  var Thingy, dom;

  dom = React.DOM;

  Thingy = React.createClass({
    render: function() {
      return dom.p({}, 'Hello World!');
    }
  });

  React.render(React.createElement(Thingy, {}), document.getElementById('my-application'));

}).call(this);
